# Generated by Django 5.2 on 2025-04-21 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmenityAdmin",
            fields=[
                (
                    "amenity_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rooms.amenity",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rooms.amenity",),
        ),
        migrations.CreateModel(
            name="RoomAdmin",
            fields=[
                (
                    "room_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="rooms.room",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("rooms.room",),
        ),
    ]
