# Generated by Django 5.2 on 2025-04-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("houses", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="price",
            new_name="price_per_night",
        ),
        migrations.AddField(
            model_name="house",
            name="pets_allowed",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="house",
            name="name",
            field=models.CharField(max_length=140),
        ),
    ]
